codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/sbt
  register:       true
  registry_token: ${{ secrets.JAVA_BUILDPACK_REGISTRY_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- id:   sbt
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       sbt-.+.tgz
    owner:      sbt
    repository: sbt
    token:      ${{ secrets.GITHUB_TOKEN }}
