# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that builds SBT-based applications from source"
  homepage = "https://github.com/paketo-buildpacks/sbt"
  id = "paketo-buildpacks/sbt"
  keywords = ["java", "sbt", "scala", "build-system"]
  name = "Paketo Buildpack for SBT"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/sbt/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "universal:packageBin"
    description = "the arguments to pass to Maven"
    name = "BP_SBT_BUILD_ARGUMENTS"

  [[metadata.configurations]]
    build = true
    default = "target/universal/*.zip"
    description = "the built application artifact explicitly.  Supersedes $BP_SBT_BUILT_MODULE"
    name = "BP_SBT_BUILT_ARTIFACT"

  [[metadata.configurations]]
    build = true
    description = "the module to find application artifact in"
    name = "BP_SBT_BUILT_MODULE"

  [[metadata.configurations]]
    build = true
    description = "the path to the SBT repositories file"
    name = "BP_SBT_REPOSITORIES_FILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "colon separated list of glob patterns, matched source files are included"
    name = "BP_INCLUDE_FILES"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "colon separated list of glob patterns, matched source files are removed"
    name = "BP_EXCLUDE_FILES"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:lightbend:sbt:1.9.1:*:*:*:*:*:*:*"]
    id = "sbt"
    name = "Scala SBT"
    purl = "pkg:generic/sbt@1.9.1"
    sha256 = "29cca5153cc96315d6e423777e5800b831e45723b47732c207a66efa5ca4fc2b"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/sbt/sbt/releases/download/v1.9.1/sbt-1.9.1.tgz"
    version = "1.9.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/sbt/sbt/blob/develop/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
